name: Bundle Extension to build/
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bundle Extension
      run: sudo apt-get install tree; ./bundle
